# Generated by Django 5.2 on 2025-07-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='father',
            field=models.CharField(default='Jahangir', max_length=50),
        ),
    ]
