# Generated by Django 5.2 on 2025-07-19 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_student_father'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='age',
            new_name='roll',
        ),
    ]
